# Generated by Django 5.2 on 2026-02-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "priority", "due_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=2
            ),
        ),
    ]
