# Generated by Django 5.2 on 2026-02-23 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_options_task_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("user", "project", "title"), name="uniq_task_title_per_project"
            ),
        ),
    ]
